<a href="https://colab.research.google.com/github/pullelamaheshbabu/Machine-Learning/blob/main/Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Part a: Create a random vector of size 15 with integers in the range 1-20
random_vector = np.random.randint(1, 21, size=15)

# 1. Reshape the array to 3 by 5
reshaped_array = random_vector.reshape(3, 5)

# 2. Print array shape
array_shape = reshaped_array.shape

# 3. Replace the max in each row by 0
for i in range(reshaped_array.shape[0]):
    reshaped_array[i, reshaped_array[i].argmax()] = 0

# Part b: Create a 2-dimensional array of size 4 x 3 with 4-byte integer elements
array_4x3 = np.zeros((4, 3), dtype=np.int32)

# Get the shape, type, and data type of the array
array_4x3_shape = array_4x3.shape
array_4x3_type = type(array_4x3)
array_4x3_dtype = array_4x3.dtype

# Print the outputs
print("Reshaped array (3x5) with max in each row replaced by 0:")
print(reshaped_array)
print("Shape of reshaped array:", array_shape)
print("\n2D array of size 4x3 with 4-byte integer elements:")
print(array_4x3)
print("Shape of 2D array:", array_4x3_shape)
print("Type of 2D array:", array_4x3_type)
print("Data type of 2D array:", array_4x3_dtype)


Reshaped array (3x5) with max in each row replaced by 0:
[[ 8  7 15  0  1]
 [ 9 18 17  0 17]
 [14 13  5  0 15]]
Shape of reshaped array: (3, 5)

2D array of size 4x3 with 4-byte integer elements:
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
Shape of 2D array: (4, 3)
Type of 2D array: <class 'numpy.ndarray'>
Data type of 2D array: int32


In [2]:
import numpy as np

# Define the square array
square_array = np.array([[3, -2], [1, 0]])

# Compute the eigenvalues and right eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(square_array)

# Print the results
print("Eigenvalues:")
print(eigenvalues)
print("\nRight Eigenvectors:")
print(eigenvectors)


Eigenvalues:
[2. 1.]

Right Eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [4]:
import numpy as np

# Define the given array
array = np.array([0, 1, 2, 3, 4, 5])

# Reshape the array into a 2x3 matrix
matrix = array.reshape(2, 3)

# Compute the sum of the diagonal elements
diagonal_sum = np.trace(matrix)

print("Sum of the diagonal elements:", diagonal_sum)



Sum of the diagonal elements: 4


In [5]:
import numpy as np

# Define the given 3x2 array
array_3x2 = np.array([[1, 2], [3, 4], [5, 6]])

# Reshape the array to 2x3
array_2x3 = array_3x2.reshape(2, 3)

# Print the reshaped array
print("Original 3x2 array:")
print(array_3x2)
print("\nReshaped 2x3 array:")
print(array_2x3)


Original 3x2 array:
[[1 2]
 [3 4]
 [5 6]]

Reshaped 2x3 array:
[[1 2 3]
 [4 5 6]]
